name: Deploy Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # ===== Build frontend =====
      - name: Install frontend deps
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          CI=false npm run build

      # ===== Deploy frontend build to server =====
      - name: Deploy frontend build
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "frontend/build/*"
          target: "/home/${{ secrets.SERVER_USER }}/project-root/sites"

      # ===== Deploy backend to server (optional) =====
      - name: Deploy backend source
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "backend/*"
          target: "/home/${{ secrets.SERVER_USER }}/project-root/backend"

      - name: Restart backend container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/project-root
            docker-compose up -d --build backend
